version: "3"

services:
  app:
    container_name: setup-nodejs
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./:/usr/src/app
    environment:
      - PORT=4000
    ports:
      - 4000:4000
